### ISSUE TITLE
Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

### ISSUE THREAD

**Issue by pascal08** [mrvautin/openKB#219]
To reproduce:

1. wrote an article
2. added title and keywords
3. clicked button 'slug from title'
4. saved article
5. searched for article

Then got the following error: `Argument passed in must be a single String of 12 bytes or a string of 24 hex characters`

**Comment by coupal** [comment]
The error comes from the common.js file, where it check if the passed article permalink is an ID or the kb_permalink to transform it to a ObjectID.

It happens if the permalink is the same size of an ObjectID. It happens only if your permalink is **exactly 24 characters**

`if (id.length !== 24) {
    return id
  }
  return ObjectID(id)`
