### ISSUE TITLE
striked through markdown seems not to work

### ISSUE THREAD

**Issue by jxsl13** [mrvautin/openKB#268]
<img width="1427" alt="bildschirmfoto 2018-09-25 um 02 28 01" src="https://user-images.githubusercontent.com/371944/45986278-d8226800-c06a-11e8-9467-908323c1edfd.png">

the in text editor preview is working fine, but sadly not the preview or articles.

**Comment by WebMatrixware** [comment]
Is this project still active? This is a relatively simple issue that has not had a response of any kind in the past nine months...

**Comment by jxsl13** [comment]
project seems dead, I found an alternative that's called bookstack.

**Comment by Steve-Mcl** [comment]
To enable strike-though is very simple as you say so I am a little concerned at having chose this project - I certainly hope its not dead.  I initially got a very quick & promising reply from @mrvautin when I wrote on an issue about mermaid charts & he said he would accept PR.  I have since created a PR (and have others almost ready too - like a fix for this issue) however now I am now getting zero response :(

Any how, If you wish to fix this yourself then...
1. In file `public/javascripts/OpenKB.js`, find code `toolbar: ['bold', 'italic', 'heading', '|'` and change it to `toolbar: ['bold', 'italic', 'strikethrough', 'heading', '|'`
1. In file `public/javascripts/OpenKB.js`, find the array `allowedTags: []` and add `'s'` element
1. In file `routes/common.js`, find the array `allowedTags: []` and add `'s'` element


`NB: Might be necessary to run `npm run uglify` before running `npm run start.`
