### ISSUE TITLE
Feature: hyperlink control

### ISSUE THREAD

**Issue by thedaftbadger** [mrvautin/openKB#51]
Suggest adding site wide setting to allow all hyperlinks to open in a new Window / Tab

**Comment by mrvautin** [comment]
Pretty easily done. Only within the article though right?

**Comment by thedaftbadger** [comment]
True..... for us that know HTML it is ok. For the other people it isnt "friendly" :)

**Comment by Collussus** [comment]
I need to point out that one of the strengths of OpenKB is that you can add markdown-it extensions. When adding a table contents extension, this breaks and rather than jumping to a part of the page it opens a new tab each. Same for wanting to do links to other pages within the website.

This should be a toggle for people who don't want it. It took me a few hours to even figure out this was a thing.

**Comment by mrvautin** [comment]
I can see how that could be annoying. I will look into that.
